#!/usr/bin/env node
/**
 * src/components/*.tsx  ->  src/index.ts
 *
 * The public entry point is generated rather than hand-maintained. Twenty-nine
 * components and their prop types is exactly the kind of list that silently
 * loses an entry: a component gets added, nobody re-exports it, and it is
 * missing from the package with no error anywhere. It still builds, still
 * passes types, and just is not there.
 *
 * Run `npm run barrel` after adding or renaming a component. The `barrel is
 * current` contract check regenerates it and fails the build if the committed
 * file disagrees.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'

/** Names that are types even though they do not end in Props. */
const TYPES_BY_NAME = new Set(['IconName', 'TooltipPlacement'])

const files = readdirSync('src/components')
  .filter((f) => f.endsWith('.tsx') && !f.includes('.stories.'))
  .sort()

const lines = []
for (const file of files) {
  const source = readFileSync(`src/components/${file}`, 'utf8')
  const names = [...source.matchAll(/^export (?:const|function|type) ([A-Za-z]+)/gm)].map((m) => m[1])

  const isType = (n) => n.endsWith('Props') || TYPES_BY_NAME.has(n)
  const values = names.filter((n) => !isType(n)).sort()
  const types = names.filter(isType).sort()
  const module = file.replace(/\.tsx$/, '')

  if (values.length) lines.push(`export { ${values.join(', ')} } from './components/${module}'`)
  if (types.length) lines.push(`export type { ${types.join(', ')} } from './components/${module}'`)
}

const header = `/**
 * Everything the library exports.
 *
 * One barrel rather than deep paths, so a consumer writes
 * \`import { Button, Card } from '@yldio/mothership-ui'\` and never has to know how
 * the source is laid out. That also means the file layout can change without
 * breaking anyone.
 *
 * Components only. The docs pages, the Foundations pages and the token scripts
 * are part of building the library, not part of using it.
 *
 * Styles are not imported here. A library that injects CSS as a side effect of
 * being imported cannot be tree-shaken and cannot have its stylesheet ordered
 * by the consumer, so the CSS ships as its own entry to import once:
 *
 *   import '@yldio/mothership-ui/styles.css'
 *
 * GENERATED by scripts/build-barrel.mjs, run \`npm run barrel\` after adding a
 * component. The \`barrel is current\` contract check fails the build if this
 * file and src/components have drifted apart.
 */
`

writeFileSync('src/index.ts', `${header}\n${lines.join('\n')}\n`)
console.log(`src/index.ts written, ${files.length} modules, ${lines.length} export statements`)
